# Custom Agent Profile for Software Development Tasks
# Optimized for complex software development and analysis tasks
# Uses OpenRouter for all models with task-aware agent mapping

# Default agent configurations (used for Atomizer, Planner, Aggregator, Verifier)
agents:
  # Atomizer: Fast decision-making with Gemini Flash
  atomizer:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 1000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1
    # Load atomizer seed prompt and demos for improved task classification
    signature_instructions: "prompt_optimization.prompts.seed_prompts.atomizer_seed:ATOMIZER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.atomizer_seed:ATOMIZER_DEMOS"

  # Planner: Strategic planning with Gemini Flash
  planner:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.1
      max_tokens: 4000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1
    # Load planner seed prompt and demos for improved task decomposition
    signature_instructions: "prompt_optimization.prompts.seed_prompts.planner_seed:PLANNER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.planner_seed:PLANNER_DEMOS"
    agent_config:
      max_subtasks: 12

  # Default Executor (fallback for unmapped task types)
  executor:
    llm:
      model: openrouter/anthropic/claude-sonnet-4.5
      temperature: 0.2
      max_tokens: 16000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1
    prediction_strategy: react
    # Load executor seed prompt and demos for improved task execution
    signature_instructions: "prompt_optimization.prompts.seed_prompts.executor_seed:EXECUTOR_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.executor_seed:EXECUTOR_DEMOS"
    agent_config:
      max_executions: 10

    # Core toolkits for software development
    toolkits:
      - class_name: E2BToolkit
        enabled: true
        toolkit_config:
          timeout: 600
          max_lifetime_hours: 23.5
          auto_reinitialize: true

      - class_name: FileToolkit
        enabled: true
        toolkit_config:
          enable_delete: false
          max_file_size: 10485760  # 10MB

      - class_name: CalculatorToolkit
        enabled: true

      - class_name: MCPToolkit
        enabled: true
        toolkit_config:
          server_name: exa
          server_type: http
          url: https://mcp.exa.ai/mcp
          headers:
            Authorization: Bearer ${oc.env:EXA_API_KEY}
          transport_type: streamable
          use_storage: false
          tool_timeout: 60

  # Aggregator: Synthesis with Gemini Flash
  aggregator:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 5000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1
    # Load aggregator seed prompt for improved result synthesis
    signature_instructions: "prompt_optimization.prompts.seed_prompts.aggregator_seed:AGGREGATOR_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.aggregator_seed:AGGREGATOR_DEMOS"

  # Verifier: Validation with Gemini Flash
  verifier:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 3000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1
    # Load verifier seed prompt and demos for improved output validation
    signature_instructions: "prompt_optimization.prompts.seed_prompts.verifier_seed:VERIFIER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.verifier_seed:VERIFIER_DEMOS"

# Task-aware agent mapping for executor
agent_mapping:
  executors:
    # RETRIEVE: Fast data fetching and research
    # Use cases: "search for documentation", "find code examples", "research best practices"
    RETRIEVE:
      llm:
        model: openrouter/google/gemini-2.5-flash  # Fast & cheap for simple queries
        temperature: 0.0  # Deterministic data retrieval
        max_tokens: 4000  # Sufficient for data responses
      prediction_strategy: react
      # Load RETRIEVE-specific seed prompt and demos
      signature_instructions: "prompt_optimization.prompts.seed_prompts.executor_retrieve_seed:EXECUTOR_RETRIEVE_PROMPT"
      demos: "prompt_optimization.prompts.seed_prompts.executor_retrieve_seed:EXECUTOR_RETRIEVE_DEMOS"
      agent_config:
        max_executions: 6  # Fewer iterations for simple retrievals

      # Research and documentation tools
      toolkits:
        - class_name: MCPToolkit
          enabled: true
          toolkit_config:
            server_name: exa
            server_type: http
            url: https://mcp.exa.ai/mcp
            headers:
              Authorization: Bearer ${oc.env:EXA_API_KEY}
            transport_type: streamable
            use_storage: false
            tool_timeout: 60

        - class_name: FileToolkit
          enabled: true
          toolkit_config:
            enable_delete: false
            max_file_size: 10485760

    # CODE_INTERPRET: Code execution, analysis, and development
    # Use cases: "implement this feature", "debug this code", "analyze performance"
    CODE_INTERPRET:
      llm:
        model: openrouter/anthropic/claude-sonnet-4.5  # Best for code generation
        temperature: 0.1  # Slightly creative for problem-solving
        max_tokens: 16000  # Large context for complex code
      prediction_strategy: react
      # Load CODE_INTERPRET-specific seed prompt and demos
      signature_instructions: "prompt_optimization.prompts.seed_prompts.executor_code_seed:EXECUTOR_CODE_PROMPT"
      demos: "prompt_optimization.prompts.seed_prompts.executor_code_seed:EXECUTOR_CODE_DEMOS"
      agent_config:
        max_executions: 15  # More iterations for debugging code

      # Code execution + file I/O + research
      toolkits:
        - class_name: E2BToolkit  # PRIMARY: Code execution
          enabled: true
          toolkit_config:
            timeout: 600
            max_lifetime_hours: 23.5
            auto_reinitialize: true

        - class_name: FileToolkit  # Save code and results
          enabled: true
          toolkit_config:
            enable_delete: false
            max_file_size: 10485760

        - class_name: CalculatorToolkit  # Mathematical calculations
          enabled: true

        - class_name: MCPToolkit  # Research and documentation
          enabled: true
          toolkit_config:
            server_name: exa
            server_type: http
            url: https://mcp.exa.ai/mcp
            headers:
              Authorization: Bearer ${oc.env:EXA_API_KEY}
            transport_type: streamable
            use_storage: false
            tool_timeout: 60

    # THINK: Deep reasoning and analysis
    # Use cases: "analyze this architecture", "compare design patterns", "reason about trade-offs"
    THINK:
      llm:
        model: openrouter/anthropic/claude-sonnet-4.5  # Best reasoning
        temperature: 0.2  # Balanced creativity + accuracy
        max_tokens: 16000  # Large context for complex reasoning
      prediction_strategy: react
      # Load THINK-specific seed prompt and demos
      signature_instructions: "prompt_optimization.prompts.seed_prompts.executor_think_seed:EXECUTOR_THINK_PROMPT"
      demos: "prompt_optimization.prompts.seed_prompts.executor_think_seed:EXECUTOR_THINK_DEMOS"
      agent_config:
        max_executions: 12  # Multiple iterations for deep analysis

      # All tools for comprehensive analysis
      toolkits:
        - class_name: E2BToolkit  # Code execution for analysis
          enabled: true
          toolkit_config:
            timeout: 600
            max_lifetime_hours: 23.5
            auto_reinitialize: true

        - class_name: MCPToolkit  # Research and context
          enabled: true
          toolkit_config:
            server_name: exa
            server_type: http
            url: https://mcp.exa.ai/mcp
            headers:
              Authorization: Bearer ${oc.env:EXA_API_KEY}
            transport_type: streamable
            use_storage: false
            tool_timeout: 60

        - class_name: FileToolkit  # Save analysis results
          enabled: true
          toolkit_config:
            enable_delete: false
            max_file_size: 10485760

        - class_name: CalculatorToolkit  # Mathematical analysis
          enabled: true

    # WRITE: Documentation, reports, and content creation
    # Use cases: "write documentation", "create README", "summarize findings"
    WRITE:
      llm:
        model: openrouter/anthropic/claude-sonnet-4.5  # Best writing quality
        temperature: 0.3  # More creative for engaging writing
        max_tokens: 16000  # Long-form content
      prediction_strategy: react
      # Load WRITE-specific seed prompt and demos
      signature_instructions: "prompt_optimization.prompts.seed_prompts.executor_write_seed:EXECUTOR_WRITE_PROMPT"
      demos: "prompt_optimization.prompts.seed_prompts.executor_write_seed:EXECUTOR_WRITE_DEMOS"
      agent_config:
        max_executions: 8  # Moderate iterations for refinement

      # File I/O + research tools
      toolkits:
        - class_name: FileToolkit  # PRIMARY: Save documents
          enabled: true
          toolkit_config:
            enable_delete: false
            max_file_size: 10485760

        - class_name: MCPToolkit  # Research and context
          enabled: true
          toolkit_config:
            server_name: exa
            server_type: http
            url: https://mcp.exa.ai/mcp
            headers:
              Authorization: Bearer ${oc.env:EXA_API_KEY}
            transport_type: streamable
            use_storage: false
            tool_timeout: 60

# Runtime configuration
runtime:
  max_depth: 6  # Deep recursion for complex software tasks
  verbose: true
  enable_logging: true
  log_level: INFO
  timeout: 120

# Resilience
resilience:
  retry:
    enabled: true
    max_attempts: 5
    strategy: exponential_backoff
    base_delay: 2.0
    max_delay: 60.0

  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 120.0
    half_open_max_calls: 3

  checkpoint:
    enabled: true
    storage_path: ${oc.env:ROMA_CHECKPOINT_PATH,.checkpoints}
    max_checkpoints: 20
    max_age_hours: 48.0
    compress_checkpoints: true
    verify_integrity: true

# Storage
storage:
  base_path: ${oc.env:STORAGE_BASE_PATH,/opt/sentient}
  max_file_size: 104857600  # 100MB

  postgres:
    enabled: ${oc.env:POSTGRES_ENABLED,true}
    connection_url: ${oc.env:DATABASE_URL,postgresql+asyncpg://localhost/roma_dspy}
    pool_size: 10
    max_overflow: 20

# Observability
observability:
  mlflow:
    enabled: ${oc.env:MLFLOW_ENABLED,false}
    tracking_uri: ${oc.env:MLFLOW_TRACKING_URI,http://mlflow:5000}
    experiment_name: ROMA-Custom-Software-Agent
    log_traces: true
    log_compiles: true
    log_evals: true

# Logging
logging:
  level: ${oc.env:LOG_LEVEL,INFO}
  log_dir: ${oc.env:LOG_DIR,logs}
  console_format: detailed
  file_format: json
  serialize: true
  rotation: 500 MB
  retention: 90 days
  colorize: true
  backtrace: true
  diagnose: false

