# Fixed Software Development Profile
# Uses correct model names that work with LiteLLM

description: "Fixed software development profile using correct model names"

# Agent configurations using correct model names
agents:
  atomizer:
    llm:
      model: anthropic/claude-3-5-haiku-20241022  # Fast and cheap
      temperature: 0.0
      max_tokens: 200  # Reduced for cost control
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.atomizer_seed:ATOMIZER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.atomizer_seed:ATOMIZER_DEMOS"

  planner:
    llm:
      model: anthropic/claude-3-5-haiku-20241022  # Good reasoning
      temperature: 0.1
      max_tokens: 300  # Reduced for cost control
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.planner_seed:PLANNER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.planner_seed:PLANNER_DEMOS"

  executor:
    llm:
      model: anthropic/claude-3-5-haiku-20241022  # Good for execution
      temperature: 0.2
      max_tokens: 400  # Reduced for cost control
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: react
    signature_instructions: "prompt_optimization.prompts.seed_prompts.executor_seed:EXECUTOR_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.executor_seed:EXECUTOR_DEMOS"
    toolkits:
      - class_name: E2BToolkit
        enabled: true
      - class_name: FileToolkit
        enabled: true
      - class_name: CalculatorToolkit
        enabled: true

  aggregator:
    llm:
      model: anthropic/claude-3-5-haiku-20241022  # Good for synthesis
      temperature: 0.0
      max_tokens: 300  # Reduced for cost control
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.aggregator_seed:AGGREGATOR_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.aggregator_seed:AGGREGATOR_DEMOS"

  verifier:
    llm:
      model: anthropic/claude-3-5-haiku-20241022  # Good for verification
      temperature: 0.0
      max_tokens: 200  # Reduced for cost control
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.verifier_seed:VERIFIER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.verifier_seed:VERIFIER_DEMOS"

# Runtime configuration
runtime:
  max_concurrency: 3
  timeout: 300
  verbose: true
  max_depth: 3
  enable_logging: true
  log_level: INFO
