# Minimal Agent Profile for Testing
# Basic configuration without external API dependencies

# Default agent configurations
agents:
  # Atomizer: Fast decision-making with Gemini Flash
  atomizer:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 1000

  # Planner: Strategic planning with Gemini Flash
  planner:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.1
      max_tokens: 4000
    agent_config:
      max_subtasks: 12

  # Default Executor
  executor:
    llm:
      model: openrouter/anthropic/claude-sonnet-4.5
      temperature: 0.2
      max_tokens: 16000
    prediction_strategy: react
    agent_config:
      max_executions: 10

    # Minimal toolkits - no external dependencies
    toolkits:
      - class_name: CalculatorToolkit
        enabled: true

  # Aggregator: Synthesis with Gemini Flash
  aggregator:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 5000

  # Verifier: Validation with Gemini Flash
  verifier:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 3000

# Runtime configuration
runtime:
  max_depth: 3
  verbose: true
  enable_logging: true
  log_level: INFO
  timeout: 120

# Resilience
resilience:
  retry:
    enabled: true
    max_attempts: 3
    strategy: exponential_backoff
    base_delay: 1.0
    max_delay: 30.0

  circuit_breaker:
    enabled: true
    failure_threshold: 3
    recovery_timeout: 60.0
    half_open_max_calls: 2

# Storage
storage:
  base_path: ${oc.env:STORAGE_BASE_PATH,/opt/sentient}
  max_file_size: 104857600  # 100MB

  postgres:
    enabled: ${oc.env:POSTGRES_ENABLED,true}
    connection_url: ${oc.env:DATABASE_URL,postgresql+asyncpg://localhost/roma_dspy}
    pool_size: 5
    max_overflow: 10

# Logging
logging:
  level: ${oc.env:LOG_LEVEL,INFO}
  log_dir: ${oc.env:LOG_DIR,logs}
  console_format: detailed
  file_format: json
  serialize: true
  rotation: 500 MB
  retention: 90 days
  colorize: true
  backtrace: true
  diagnose: false

