# OpenRouter Test Profile
# Simple configuration to test OpenRouter integration

agents:
  atomizer:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 1000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1

  planner:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.1
      max_tokens: 4000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1
    agent_config:
      max_subtasks: 12

  executor:
    llm:
      model: openrouter/anthropic/claude-sonnet-4.5
      temperature: 0.2
      max_tokens: 16000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1
    prediction_strategy: react
    agent_config:
      max_executions: 10

    toolkits:
      - class_name: CalculatorToolkit
        enabled: true

  aggregator:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 5000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1

  verifier:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 3000
      api_key: ${oc.env:OPENROUTER_API_KEY,null}
      api_base: https://openrouter.ai/api/v1

runtime:
  max_depth: 3
  verbose: true
  enable_logging: true
  log_level: INFO
  timeout: 120

resilience:
  retry:
    enabled: true
    max_attempts: 3
    strategy: exponential_backoff
    base_delay: 1.0
    max_delay: 30.0

  circuit_breaker:
    enabled: true
    failure_threshold: 3
    recovery_timeout: 60.0
    half_open_max_calls: 2

storage:
  base_path: ${oc.env:STORAGE_BASE_PATH,/opt/sentient}
  max_file_size: 104857600

  postgres:
    enabled: ${oc.env:POSTGRES_ENABLED,true}
    connection_url: ${oc.env:DATABASE_URL,postgresql+asyncpg://localhost/roma_dspy}
    pool_size: 5
    max_overflow: 10

logging:
  level: ${oc.env:LOG_LEVEL,INFO}
  log_dir: ${oc.env:LOG_DIR,logs}
  console_format: detailed
  file_format: json
  serialize: true
  rotation: 500 MB
  retention: 90 days
  colorize: true
  backtrace: true
  diagnose: false
