# Optimized Software Development Profile
# Uses the best direct provider models for each task type
# Cost-effective and high-performance configuration

description: "Optimized software development profile using best direct provider models for each task"

# Agent configurations optimized for software development
agents:
  # Atomizer: Ultra-fast with Gemini Flash (cheapest)
  atomizer:
    llm:
      model: gemini-2.5-flash
      temperature: 0.0
      max_tokens: 2000
      api_key: ${oc.env:GOOGLE_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.atomizer_seed:ATOMIZER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.atomizer_seed:ATOMIZER_DEMOS"
    agent_config:
      confidence_threshold: 0.8
      max_classifications: 5

  # Planner: Strategic planning with Claude Sonnet (best reasoning)
  planner:
    llm:
      model: claude-sonnet-3.5
      temperature: 0.1
      max_tokens: 8000
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.planner_seed:PLANNER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.planner_seed:PLANNER_DEMOS"
    agent_config:
      max_subtasks: 15
      planning_depth: 3
      include_dependencies: true

  # Default Executor: Claude Sonnet for complex tasks
  executor:
    llm:
      model: claude-sonnet-3.5
      temperature: 0.2
      max_tokens: 16000
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: react
    signature_instructions: "prompt_optimization.prompts.seed_prompts.executor_seed:EXECUTOR_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.executor_seed:EXECUTOR_DEMOS"
    agent_config:
      max_executions: 10
      timeout: 300
      retry_attempts: 3
    toolkits:
      - class_name: E2BToolkit
        enabled: true
        toolkit_config:
          timeout: 600
          max_lifetime_hours: 23.5
          auto_reinitialize: true
      - class_name: FileToolkit
        enabled: true
        toolkit_config:
          allowed_extensions: [".py", ".js", ".ts", ".jsx", ".tsx", ".java", ".cpp", ".c", ".h", ".go", ".rs", ".php", ".rb", ".swift", ".kt", ".scala", ".sh", ".yaml", ".yml", ".json", ".xml", ".html", ".css", ".scss", ".sql", ".md", ".txt"]
          max_file_size: 10485760  # 10MB
      - class_name: CalculatorToolkit
        enabled: true

  # Aggregator: Claude Sonnet for synthesis
  aggregator:
    llm:
      model: claude-sonnet-3.5
      temperature: 0.0
      max_tokens: 12000
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.aggregator_seed:AGGREGATOR_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.aggregator_seed:AGGREGATOR_DEMOS"
    agent_config:
      synthesis_strategy: hierarchical
      include_metadata: true

  # Verifier: Claude Sonnet for quality assurance
  verifier:
    llm:
      model: claude-sonnet-3.5
      temperature: 0.0
      max_tokens: 8000
      api_key: ${oc.env:ANTHROPIC_API_KEY,null}
    prediction_strategy: chain_of_thought
    signature_instructions: "prompt_optimization.prompts.seed_prompts.verifier_seed:VERIFIER_PROMPT"
    demos: "prompt_optimization.prompts.seed_prompts.verifier_seed:VERIFIER_DEMOS"
    agent_config:
      verification_level: strict
      include_tests: true

# Task-aware agent mapping for specialized software development tasks
agent_mapping:
  executors:
    # Code generation: Claude Sonnet for quality code
    CODE_GENERATE:
      llm:
        model: claude-sonnet-3.5
        temperature: 0.1
        max_tokens: 16000
        api_key: ${oc.env:ANTHROPIC_API_KEY,null}
      prediction_strategy: react
      toolkits:
        - class_name: E2BToolkit
          enabled: true
        - class_name: FileToolkit
          enabled: true
      agent_config:
        max_executions: 15
        code_style: "clean"
        include_comments: true

    # Code review: Claude Sonnet for thorough analysis
    CODE_REVIEW:
      llm:
        model: claude-sonnet-3.5
        temperature: 0.0
        max_tokens: 12000
        api_key: ${oc.env:ANTHROPIC_API_KEY,null}
      prediction_strategy: chain_of_thought
      toolkits:
        - class_name: FileToolkit
          enabled: true
        - class_name: E2BToolkit
          enabled: true
      agent_config:
        review_depth: comprehensive
        include_suggestions: true

    # Testing: Claude Sonnet for comprehensive testing
    TEST_DEBUG:
      llm:
        model: claude-sonnet-3.5
        temperature: 0.1
        max_tokens: 10000
        api_key: ${oc.env:ANTHROPIC_API_KEY,null}
      prediction_strategy: react
      toolkits:
        - class_name: E2BToolkit
          enabled: true
        - class_name: FileToolkit
          enabled: true
      agent_config:
        test_coverage: high
        debug_level: detailed

    # Documentation: Claude Sonnet for clear docs
    DOCUMENT:
      llm:
        model: claude-sonnet-3.5
        temperature: 0.2
        max_tokens: 8000
        api_key: ${oc.env:ANTHROPIC_API_KEY,null}
      prediction_strategy: chain_of_thought
      toolkits:
        - class_name: FileToolkit
          enabled: true
      agent_config:
        doc_style: comprehensive
        include_examples: true

    # Research: Claude Sonnet for thorough research
    RESEARCH:
      llm:
        model: claude-sonnet-3.5
        temperature: 0.1
        max_tokens: 12000
        api_key: ${oc.env:ANTHROPIC_API_KEY,null}
      prediction_strategy: chain_of_thought
      toolkits:
        - class_name: FileToolkit
          enabled: true
      agent_config:
        research_depth: thorough
        include_sources: true

    # Architecture: Claude Sonnet for system design
    ARCHITECT:
      llm:
        model: claude-sonnet-3.5
        temperature: 0.1
        max_tokens: 16000
        api_key: ${oc.env:ANTHROPIC_API_KEY,null}
      prediction_strategy: chain_of_thought
      toolkits:
        - class_name: FileToolkit
          enabled: true
        - class_name: CalculatorToolkit
          enabled: true
      agent_config:
        design_principles: solid
        include_diagrams: true

# Runtime configuration optimized for software development
runtime:
  max_concurrency: 6
  timeout: 300  # 5 minutes (max allowed)
  verbose: true
  max_depth: 4  # Allow deeper recursion for complex software tasks
  enable_logging: true
  log_level: INFO
  
  cache:
    enabled: true
    enable_disk_cache: true
    enable_memory_cache: true
    disk_cache_dir: .cache/dspy
    disk_size_limit_bytes: 50000000000  # 50GB for large codebases
    memory_max_entries: 2000000

# Resilience configuration for development tasks
resilience:
  retry_strategy: exponential_backoff
  max_retries: 5
  base_delay: 2.0
  max_delay: 60.0
  
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 120.0
    half_open_max_calls: 3

# Storage configuration for development artifacts
storage:
  base_path: ${oc.env:STORAGE_BASE_PATH,/opt/sentient}
  max_file_size: 104857600  # 100MB for large files
  
  postgres:
    enabled: ${oc.env:POSTGRES_ENABLED,true}
    connection_url: ${oc.env:DATABASE_URL,postgresql+asyncpg://roma:roma@localhost:5432/roma_dspy}
    pool_size: 10
    max_overflow: 20

# Logging configuration for development
logging:
  level: INFO
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file: logs/optimized_software_dev_{time:YYYY-MM-DD}.log
  rotation: "1 day"
  retention: "30 days"
